project:
  type: website
  output-dir: _site

engine: markdown  

website:
  title: "Manual for dealing with data in research projects"
  sidebar:
    style: "floating"
    search: true

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    number-sections: true
    code-fold: true

author: 
  - name: "Statistikernätverket Forum Norr"
    url: https://canvas.umu.se/courses/2600

execute:
  freeze: true
