name: Publicera Quarto-dokument

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Rendera dokument med befintlig layout
        run: |
          quarto render --no-execute

      - name: Publicera på GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # Om _quarto.yml sparar på annat ställe (t.ex. docs eller output), ändra här!
          publish_branch: gh-pages
